DROP TABLE IF EXISTS TB_MEMBRO;
create table TB_MEMBRO
(
    COD_MEMBRO bigint auto_increment	primary key,
    TX_STATUS VARCHAR(255),
    TX_CGP VARCHAR(255),
    TX_CPF VARCHAR(11),
    TX_NOME VARCHAR(255),
    TX_CARGO VARCHAR(255),
    TX_TITULO_HONORIFICO VARCHAR(255),
    TX_TIPO_SANGUINEO VARCHAR(2),
    DT_NASCIMENTO VARCHAR(255),
    COD_ENDERECO bigint,
    foreign key (COD_MEMBRO) references TB_MEMBRO(COD_MEMBRO)
);

DROP TABLE IF EXISTS TB_USUARIO;
CREATE TABLE TB_USUARIO (
    COD_USUARIO bigint auto_increment	primary key,
    TX_NOME VARCHAR(255),
    TX_CPF VARCHAR(255),
    TX_SENHA VARCHAR(255),
    TX_LOGIN VARCHAR(255)
);

DROP TABLE IF EXISTS TB_NOTIFICACAO;
CREATE TABLE TB_NOTIFICACAO (
    COD_NOTIFICACAO bigint auto_increment	primary key,
    TX_TITULO VARCHAR(255),
    TX_MENSAGEM TEXT
);

DROP TABLE IF EXISTS TB_ENDERECO;
CREATE TABLE TB_ENDERECO (
    COD_ENDERECO bigint auto_increment	primary key,
    TX_CPF VARCHAR(13),
    TX_CIDADE VARCHAR(255),
    TX_UF VARCHAR(2),
    TX_CEP VARCHAR(255)
);

DROP TABLE IF EXISTS TB_CORPO_FILOSOFICO;
CREATE TABLE TB_CORPO_FILOSOFICO (
    COD_CORPO_FILOSOFICO bigint auto_increment	primary key,
    TX_GRAU VARCHAR(13),
    TX_CORPO VARCHAR(255),
    DT_GRAU VARCHAR(255)
);

DROP TABLE IF EXISTS TB_MEMBRO_CORPO_FILOSOFICO;
CREATE TABLE TB_MEMBRO_CORPO_FILOSOFICO (
   COD_MEMBRO bigint,
   COD_CORPO_FILOSOFICO bigint,

   foreign key (COD_MEMBRO) references TB_MEMBRO(COD_MEMBRO),
   foreign key (COD_CORPO_FILOSOFICO) references TB_CORPO_FILOSOFICO(COD_CORPO_FILOSOFICO)
);


